services:
  nginx:
    image: nginx
    ports:
      - "80:80"
#      - "443:443"
    volumes:
      - .:/var/www/html
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
#      - ./certbot/www/:/var/www/certbot/:ro
    depends_on:
      - php
    env_file: ".env"
  php:
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    env_file: ".env"
    depends_on:
      - db
  redis:
    image: redis
  db:
    image: mysql
    env_file: ".env"
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    env_file: ".env"
    ports:
      - "8080:80"
#  certbot:
#    image: certbot/certbot:latest
#    volumes:
#      - ./certbot/www/:/var/www/certbot/:rw
#      - ./certbot/conf/:/etc/letsencrypt/:rw
#    depends_on:
#      - nginx